# This is a basic workflow to help you get started with Actions

name: CI-server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
   # branches: [ "main" ]
 # pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    timeout-minutes: 9900
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setting up...
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/rangagtlab/light-manager/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      # Runs a set of commands using the runners shell
      - name: Connecting...
        run: cmd /c show.bat
      
      - name: Looping...
        run: cmd /c loop.bat

